# Site settings
title: "Yoshiki Satou"
description: "I am deep dive into Ruby on Rails Web Developer"


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Yoshiki Satou"
resume_name_jp:                 "Yoshiki Satou Portfolio"
resume_title:                   "Deep Dive Into Ruby on Rails"

# used for the contact button in _layouts/resume.html
resume_contact_email:           ""

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>Ruby on Rails を得意とるするバックエンドエンジニアを目指しています。</p><p>インフラ構築のナレッジも深めていきたい。</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true
resume_experience_summary: "<p>個人事業者として独立開業し、音楽をモチーフにしたオリジナル雑貨のネットショップやUGCサイトを開発しました。</p><p>現在は、観光施設運営会社において、業務フロー効率化を進めるべく社内SEに従事しています。</p>"
# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/wholetonemusic"
  # resume_twitter_url:           "https://twitter.com/wholetone"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yoshiki-satou-72524a21b/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://guitar-cv.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
